// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qjehcyogixkoixipkulc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InFqZWhjeW9naXhrb2l4aXBrdWxjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTkwMTc2MjQsImV4cCI6MjA3NDU5MzYyNH0.IzbPFO0XEX7QNVCZE_qdvCCPE0Jm7gI7ZVlCYh-ymUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});